version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node/10
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn style

      - run: yarn test

      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "registry=https://registry.npmjs.org/" > ~/repo/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/repo/.npmrc
      - run: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.+/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.+/
